### ISSUE TITLE
IrcChannel.Users.UsersByMode only returns those users who actually have a mode

### ISSUE THREAD

**Issue by RockyTV** [SirCmpwn/ChatSharp#31]
I don't know if it was the purpose of the UsersByMode dictionary. It does only return those users that have a mode set.

EDIT: users who don't have a mode are not included in the dictionary.

**Comment by SirCmpwn** [comment]
I'm not sure I understand what the issue is. Would you have users without a mode be included in the dictionary with ' ' as the key or something?

**Comment by RockyTV** [comment]
Yes. Users who don't have a mode are not included in the UsersByMode dictionary.

**Comment by SirCmpwn** [comment]
Right, so if they don't have a mode then why would they be in that dictionary?

**Comment by RockyTV** [comment]
Sorry, I can't explain it correctly.

> Right, so if they don't have a mode then why would they be in that dictionary?
UsersByMode return an UserCollection containing the users that have the same mode. Why not include the "mode-less" users, so the dictionary can be complete?

One other way of solving this is saving other users modes in the Modes object, and I think it would require a rework.

**Comment by SirCmpwn** [comment]
So user modes are identified with a character. Operators are '@'. Voice is '+'. There are different ones depending on which network you're on. What character would you suggest is used for users without a mode?

**Comment by RockyTV** [comment]
I'd suggest using an empty char, like you said: ' '

**Comment by SirCmpwn** [comment]
That doesn't really sit right with me. I guess if you feel strongly about it, send a pull request.

**Comment by RockyTV** [comment]
Or, instead of supplying an empty mode, just store the user's channel mode in the Mode object.

**Comment by SirCmpwn** [comment]
That works, too.

**Comment by SirCmpwn** [comment]
Channel.UsersByMode[null] is now what you're looking for.

**Comment by RockyTV** [comment]
Thank you very much!
