### ISSUE TITLE
Sending a WHOIS raw message crashes the library

### ISSUE THREAD

**Issue by RockyTV** [SirCmpwn/ChatSharp#32]
If you send a `WHOIS personname` raw message, ChatSharp crashes with a NullReferenceException at **[RequestManager.cs line 26](https://github.com/SirCmpwn/ChatSharp/blob/master/ChatSharp/RequestManager.cs#L26)**.

**Comment by SirCmpwn** [comment]
This is because that when the response comes back from the server, ChatSharp doesn't have a reference to the original WHOIS request. The appropriate way to do a WHOIS with ChatSharp is like so:

    client.WhoIs("name", whois => { /* do something with the result */ });
