### ISSUE TITLE
issues with twitch servers

### ISSUE THREAD

**Issue by seranus** [SirCmpwn/ChatSharp#35]
They don't fill the server info. the issue when serverInfo is null

code breaks at private message class
if (serverInfo.ChannelTypes.Any(c => Source.StartsWith(c.ToString())))
 
When the channels that are large your don't get the whole user list only mods and admins, your getting exceptions, kinda handled, on almost every message because

 var u = channel.Users[eventArgs.PrivateMessage.User.Nick]; KeyNotFound

**Comment by SirCmpwn** [comment]
ServerInfo now assumes a list of sane defaults, and will never be null.

**Comment by SimStm** [comment]
I'm getting the same issue with the trunk version. I've used the NuGet DLL version first, and works like a charm, but I need to create some new events to error treatment but serverInfo gets null with some properties everytime.
