### ISSUE TITLE
Crash when a channel is -n and some outsider says something

### ISSUE THREAD

**Issue by fahadash** [SirCmpwn/ChatSharp#38]
When bot sees a PRIVMSG into a channel, the code at the following line does not find that user's record among the members and crashes

https://github.com/SirCmpwn/ChatSharp/blob/master/ChatSharp/UserCollection.cs#L62

**Comment by SirCmpwn** [comment]
I've been running several bots in production for a few years now on ChatSharp in channels that are -n and see frequent outside messages.

**Comment by fahadash** [comment]
The exception is swallowed. It should now be thrown by that method in first place IMO
