### ISSUE TITLE
Userpool

### ISSUE THREAD

**Issue by GrantBartlett** [SirCmpwn/ChatSharp#47]
Hi - this is great, appreciate the library a lot.

No problem so far. I'm just looking at displaying users. Could you give an example on getting a list of users in a channel.

Thanks for any help

**Comment by SirCmpwn** [comment]
client.Channels["#example"].Users

**Comment by GrantBartlett** [comment]
Sweet. Appreciate the reply. 
Debug.Write returns ChatSharp.UserCollection. Is that correct? How do I get an object of that or don't I?

**Comment by GrantBartlett** [comment]
@SirCmpwn ?
