### ISSUE TITLE
ServerInformationReceived Event called 3 times in a row

### ISSUE THREAD

**Issue by maxpa1n87** [SirCmpwn/ChatSharp#51]
I have created one instance of IrcClient and added the ServerInformationReceived event. Calling the AsyncConnect method first fires my also added ConnectionComplete event and then ServerInformationReceived gets called 3 times in a row. Is this intended or is it a bug? The server ist chat.freenode.net on port 6667.

**Comment by SirCmpwn** [comment]
Can you capture `RawMessageReceived` and log it somewhere? I'd be interested to see what it shows.

**Comment by maxpa1n87** [comment]
I have logged RawMessageReceived and it says the following using chat.freenode.net 6667:
:adams.freenode.net NOTICE * :*** Looking up your hostname...
:adams.freenode.net NOTICE * :*** Checking Ident
:adams.freenode.net NOTICE * :*** Found your hostname
:adams.freenode.net NOTICE * :*** No Ident response
:adams.freenode.net 001 maxpa1n87 :Welcome to the freenode Internet Relay Chat Network maxpa1n87
:adams.freenode.net 002 maxpa1n87 :Your host is adams.freenode.net[94.125.182.252/6667], running version ircd-seven-1.1.3
:adams.freenode.net 003 maxpa1n87 :This server was created Mon Jul 20 2015 at 16:58:36 UTC
:adams.freenode.net 004 maxpa1n87 adams.freenode.net ircd-seven-1.1.3 DOQRSZaghilopswz CFILMPQSbcefgijklmnopqrstvz bkloveqjfI
:adams.freenode.net 005 maxpa1n87 CHANTYPES=# EXCEPTS INVEX CHANMODES=eIbq,k,flj,CFLMPQScgimnprstz CHANLIMIT=#:120 PREFIX=(ov)@+ MAXLIST=bqeI:100 MODES=4 NETWORK=freenode KNOCK STATUSMSG=@+ CALLERID=g :are supported by this server
:adams.freenode.net 005 maxpa1n87 CASEMAPPING=rfc1459 CHARSET=ascii NICKLEN=16 CHANNELLEN=50 TOPICLEN=390 ETRACE CPRIVMSG CNOTICE DEAF=D MONITOR=100 FNC TARGMAX=NAMES:1,LIST:1,KICK:1,WHOIS:1,PRIVMSG:4,NOTICE:4,ACCEPT:,MONITOR: :are supported by this server
:adams.freenode.net 005 maxpa1n87 EXTBAN=$,ajrxz WHOX CLIENTVER=3.0 SAFELIST ELIST=CTU :are supported by this server
:adams.freenode.net 251 maxpa1n87 :There are 162 users and 92674 invisible on 26 servers
:adams.freenode.net 252 maxpa1n87 25 :IRC Operators online
:adams.freenode.net 253 maxpa1n87 8 :unknown connection(s)
:adams.freenode.net 254 maxpa1n87 63428 :channels formed
:adams.freenode.net 255 maxpa1n87 :I have 5876 clients and 1 servers
:adams.freenode.net 265 maxpa1n87 5876 5904 :Current local users 5876, max 5904
:adams.freenode.net 266 maxpa1n87 92836 94396 :Current global users 92836, max 94396
:adams.freenode.net 250 maxpa1n87 :Highest connection count: 5905 (5904 clients) (673447 connections received)
:adams.freenode.net 375 maxpa1n87 :- adams.freenode.net Message of the Day - 
:adams.freenode.net 372 maxpa1n87 :- Welcome to adams.freenode.net. Thanks to ATW Internet Kft 
:adams.freenode.net 372 maxpa1n87 :- (http://www.atw.hu) for sponsoring this server!
:adams.freenode.net 372 maxpa1n87 :-  
:adams.freenode.net 372 maxpa1n87 :- ADAMS, DOUGLAS (1952-2001).  Author of The Hitch Hikers Guide
:adams.freenode.net 372 maxpa1n87 :- to the Galaxy and many other witty and humourous books,
:adams.freenode.net 372 maxpa1n87 :- portrayed in his uniquely British irony. He is sorely missed
:adams.freenode.net 372 maxpa1n87 :- by many millions of devoted fans. "So long and thanks for all
:adams.freenode.net 372 maxpa1n87 :- the books!"
:adams.freenode.net 372 maxpa1n87 :-  
:adams.freenode.net 372 maxpa1n87 :- Welcome to freenode - supporting the free and open source
:adams.freenode.net 372 maxpa1n87 :- software communities since 1998.
:adams.freenode.net 372 maxpa1n87 :-  
:adams.freenode.net 372 maxpa1n87 :- By connecting to freenode you indicate that you have read and
:adams.freenode.net 372 maxpa1n87 :- accept our policies as set out on http://www.freenode.net
:adams.freenode.net 372 maxpa1n87 :- freenode runs an open proxy scanner. Please join #freenode for
:adams.freenode.net 372 maxpa1n87 :- any network-related questions or queries, where a number of
:adams.freenode.net 372 maxpa1n87 :- volunteer staff and helpful users will be happy to assist you.
:adams.freenode.net 372 maxpa1n87 :-  
:adams.freenode.net 372 maxpa1n87 :- You can meet us at FOSSCON (http://www.fosscon.org) where we get
:adams.freenode.net 372 maxpa1n87 :- together with like-minded FOSS enthusiasts for talks and
:adams.freenode.net 372 maxpa1n87 :- real-life collaboration.
:adams.freenode.net 372 maxpa1n87 :-  
:adams.freenode.net 372 maxpa1n87 :- We would like to thank Private Internet Access
:adams.freenode.net 372 maxpa1n87 :- (https://www.privateinternetaccess.com/) and the other
:adams.freenode.net 372 maxpa1n87 :- organisations that help keep freenode and our other projects
:adams.freenode.net 372 maxpa1n87 :- running for their sustained support.
:adams.freenode.net 372 maxpa1n87 :-  
:adams.freenode.net 372 maxpa1n87 :- In particular we would like to thank the sponsor
:adams.freenode.net 372 maxpa1n87 :- of this server, details of which can be found above.
:adams.freenode.net 372 maxpa1n87 :-  
:adams.freenode.net 376 maxpa1n87 :End of /MOTD command.
:maxpa1n87 MODE maxpa1n87 :+i
:NickServ!NickServ@services. NOTICE maxpa1n87 :maxpa1n87 is not a registered nickname.
:adams.freenode.net 311 maxpa1n87 maxpa1n87 ~maxpa1n87 ip5f5acc3e.dynamic.kabel-deutschland.de * :Max Hölzer
:adams.freenode.net 312 maxpa1n87 maxpa1n87 adams.freenode.net :Budapest, HU, EU
:adams.freenode.net 378 maxpa1n87 maxpa1n87 :is connecting from *@ip5f5acc3e.dynamic.kabel-deutschland.de 95.90.204.62
:adams.freenode.net 317 maxpa1n87 maxpa1n87 6 1442416751 :seconds idle, signon time
:adams.freenode.net 318 maxpa1n87 maxpa1n87 :End of /WHOIS list.
