### ISSUE TITLE
How to see who sended the command?

### ISSUE THREAD

**Issue by tim241** [SirCmpwn/ChatSharp#62]
How t osee who sended the command because I need to get the name in an string because I am creating an tokensystem so I need to save that :)

**Comment by theTwist84** [comment]
Here are some things I'd like to know:

1. What command are you talking about?
2. Is the user sending it as a private message or from a channel?
3. How old are you, is English your first language?

**Comment by tim241** [comment]
1: I check for a command in the IRC chat(in this instance !Tokens_add, then I want to save the value after that, and I want to add from who it is otherwhise I can't create an tokensystem)
2: channel
3: I am 14, and English is not my native language, sorry my grammar was bad in that question but most of the time I am pretty good with English.(I am learning C#, I know vb.net already)

**Comment by tim241** [comment]
And because there is no large community I ask the questions here.

**Comment by theTwist84** [comment]
This is how I would do it, note that the client is the same as before
http://pastebin.com/Q3g05zE7

Feel free to use and/or modify it to fit your needs.

**Comment by theTwist84** [comment]
If you have any other queries feel free peruse the main part of my own ChatShart implementation [found here](https://github.com/theTwist84/IRC_App/blob/master/IRC_App/IRC_App/Program.cs#L241-L683)

**Comment by tim241** [comment]
Thanks :)
